<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<html>
<head>
  <title>管理控制台首页</title>
</head>
<body>
<h2>欢迎使用XXX系统管理控制台</h2>
<p>通过控制台可以进行：</p>
<ul>
  <li>用户管理</li>
  <li>应用模块管理</li>
  <li>角色管理
    <ul>
      <li>哪些角色能够访问使用哪些应用模块</li>
    </ul>
  </li>
  <li>授权管理
    <ul>
      <li>哪些用户拥有哪些角色</li>
    </ul>
  </li>
</ul>
</body>
</html>
